const topics = [
	"Dune",
	"Blade Runner",
	"The Matrix",
	"Neuromancer",
	"The Expanse",
	"Foundation",
	"Snow Crash",
	"Star Trek",
	"Star Wars",
	"Arrival",
	"The Big Bang Theory",
	"Ready Player One",
	"Hackers",
	"The IT Crowd",
	"Silicon Valley",
	"Tron",
	"Ender’s Game",
	"WarGames",
	"Hitchhiker's Guide to the Galaxy",
	"Doctor Who",
	"Monty Python and the Holy Grail",
	"Spaceballs",
	"Galaxy Quest",
	"Rick and Morty",
	"Futurama",
	"The Office",
	"Parks and Recreation",
	"Community",
	"Archer",
	"Shaun of the Dead",
	"Arrakis",
	"The Death Star",
	"Vulcan",
	"Tatooine",
	"The Citadel (Mass Effect)",
	"Pandora (Avatar)",
	"Hogwarts",
	"The Shire",
	"Rivendell",
	"Cloud City",
	"Elysium",
	"Terminator",
	"Stargate",
	"Black Mirror",
	"Westworld",
	"The Mandalorian",
	"Guardians of the Galaxy",
	"The Avengers",
	"Interstellar",
	"Inception",
	"Contact",
	"Minority Report",
	"Eternal Sunshine of the Spotless Mind",
	"The Prestige",
	"Dark",
	"Altered Carbon",
	"Stranger Things",
	"The Orville",
	"Battlestar Galactica",
	"Andromeda",
	"Farscape",
	"Cowboy Bebop",
	"Akira",
	"Ghost in the Shell",
	"Wall-E",
	"I, Robot",
	"The Jetsons",
	"Metropolis",
	"Logan's Run",
	"A Clockwork Orange",
	"RoboCop",
	"The Fifth Element",
	"The Time Machine",
	"Jurassic Park",
	"Her",
	"The Day the Earth Stood Still",
	"2001: A Space Odyssey",
	"2010: The Year We Make Contact",
	"Moon",
	"Solaris",
	"Pitch Black",
	"Chronicles of Riddick",
	"Mad Max: Fury Road",
	"Waterworld",
	"Total Recall",
	"Event Horizon",
	"Gattaca",
	"Stalker",
	"The Thing",
	"Alien",
	"Aliens",
	"Predator",
	"The Abyss",
	"Super 8",
	"Cloverfield",
	"Pacific Rim",
	"Edge of Tomorrow",
	"Oblivion",
	"Love, Death & Robots",
];

export default topics;
